[tool.black]
line-length = 88
target-version = [ "py38",]
include = "\\.pyi?$"
exclude = "(\n  /(\n    | \\.git\n  )/\n)\n"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
profile = "black"
