from enum import Enum


class TestShopNames(Enum):
    AMAZON = ("AMAZON",)
    TARGET = ("TARGET",)
    WALMART = ("WALMART",)
    TJMAXX = ("TJMAXX",)
    GOOGLE = ("GOOGLE",)
    NEWEGG = ("NEWEGG",)
    HM = ("HM",)
    MICROCENTER = ("MICROCENTER",)
    FASHIONNOVA = ("FASHIONNOVA",)
    SIXPM = ("SIXPM",)
    POSHMARK = ("POSHMARK",)
    MACYS = ("MACYS",)
    ASOS = ("ASOS",)
    JCPENNEY = ("JCPENNEY",)
    KOHLS = "KOHLS"
    FOOTLOCKER = ("FOOTLOCKER",)
    BESTBUY = ("BESTBUY",)
    EBAY = ("EBAY",)
    KMART = ("KMART",)
    BIGLOTS = ("BIGLOTS",)
    BURLINGTON = ("BURLINGTON",)
    MVMTWATCHES = ("MVMTWATCHES",)
    BOOHOO = ("BOOHOO",)
    FOREVER21 = ("FOREVER21",)
    STYLERUNNER = ("STYLERUNNER",)
    LEVI = ("LEVI",)
    ZARA = ("ZARA",)
    NORDSTROM = "NORDSTROM"
    NORDSTROMRACK = "NORDSTROMRACK"
    HAUTELOOK = "HAUTELOOK"
    SAKSFIFTHAVENUE = "SAKSFIFTHAVENUE"
    EXPRESS = "EXPRESS"
    CHARLOTTERUSSE = "CHARLOTTERUSSE"
    ALDO = "ALDO"
    SHOPQUEEN = "SHOPQUEEN"
    NIKE = "NIKE"
    ADIDAS = "ADIDAS"
    DICKSSPORTINGGOODS = "DICKSSPORTINGGOODS"
    BINK = "BINK"
